### ISSUE TITLE
XCode 15, Dropbox SDK 7.11. App validation crash.

### ISSUE THREAD

**Issue by SirManburger** [dropbox/dropbox-sdk-obj-c#374] opened 2023-10-10 13:55 UTC
XCode 15, Deplyoment target iOS 12, Mac OS Sonoma.
When trying to validate my bundle with new Dropbox - Xcode crashes.
Skipped validation and sent to distribution as is, yet AppStore Connect can't send the bundle to review.
Previous version of Dropbox works fine.

**Comment by greg-db** [comment] 2023-10-10 19:56
We heard about some general issues with Xcode 15 and the upload process crashing earlier today, apparently due to some issues on Apple's side. Are you still seeing this crash now?

**Comment by inPhilly** [comment] 2023-11-17 02:15
Did you find a way for this to pass validation? Are there any other options for objective-C apps for Dropbox?

**Comment by inPhilly** [comment] 2023-11-17 02:21
Is this the same issue? "Invalid bundle structure. The “MyApp.app/DTBiOSSDK.framework.dSYM/Contents/Resources/DWARF/DTBiOSSDK” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle (ID: c264b81c-f615-4c82-978a-45bf7e84f945)"

**Comment by greg-db** [comment] 2023-11-17 18:16
@inPhilly We didn't hear back on the original issue here, so I'm going to close this out.

It's unclear if/how the error you're getting is related to the Dropbox SDK in particular as it doesn't mention "Dropbox", but if you're currently seeing an issue with the Dropbox SDK, please [open a new issue](https://github.com/dropbox/dropbox-sdk-obj-c/issues/new) with as much detail as possible, such as any/all errors or output you're getting and the steps to reproduce the issue, so we can look into it. Thanks!

**Closed by greg-db** 2023-11-17 18:16 UTC
