### ISSUE TITLE
ld: framework not found 

### ISSUE THREAD

**Issue by holyman2k** [dropbox/dropbox-sdk-obj-c#56] opened 2016-10-24 00:46 UTC
Hi, I run into an issue with this library using cocoapods
I recieved an compile time error on a plain project 
ld: framework not found Webkit
clang: error: linker command failed with exit code 1 (use -v to see invocation)

the Podfile 

platform :ios, '10.0'
use_frameworks!

target 'TestDropbox' do

pod 'ObjectiveDropboxOfficial'

end

Anyone have any ideas why? ps removing use_frameworks! does not help

**Comment by greg-db** [comment] 2016-10-24 20:18
Hi @holyman2k , what version of Xcode are you using, and what's your project's deployment target? Thanks in advance!

**Comment by holyman2k** [comment] 2016-11-01 00:29
XCode 8.1 and deployment target 8.0.
I've tested with deployment target 10.0 and still have the same error

**Comment by greg-db** [comment] 2016-11-01 00:34
Thanks! We'll look into it.

**Comment by holyman2k** [comment] 2016-11-01 00:51
Thank you Greg

**Comment by mylaneza** [comment] 2016-11-01 17:36
The same problem here XCode 8.0 target ios 8.0

**Comment by scobbe** [comment] 2016-11-08 03:30
@mylaneza and @holyman2k: Sorry for the delay on our end in getting back to you here.

Could you both confirm with me that you have the .xcworkspace file open and NOT the .xcodeproj file? Sometimes these framework linking issues arise from that.

If you do have the .xcworkspace open, we can debug additionally and get to the bottom of this. Thanks for your patience.

**Comment by scobbe** [comment] 2016-11-08 03:34
If the above isn't the problem you're having, would you mind sending me a screenshot of this menu in your project:

![image](https://cloud.githubusercontent.com/assets/17483354/20085920/2bcd3b4a-a521-11e6-82fa-854e27904dd7.png)

**Comment by holyman2k** [comment] 2016-11-08 23:50
sorry for the delay in response:
![screen shot 2016-11-09 at 10 49 47 am](https://cloud.githubusercontent.com/assets/729313/20122220/4a22e7ee-a66a-11e6-9bbc-a06ea0eac834.png)

**Comment by holyman2k** [comment] 2016-11-08 23:52
Also I'm using xcode on a case sensitive disk, I'm not sure if that's causing the problem.

**Comment by mylaneza** [comment] 2016-11-08 23:58
2016-11-08 17:52 GMT-06:00 holyman2k <notifications@github.com>:

**Comment by scobbe** [comment] 2016-11-09 18:06
@holyman2k @mylaneza: Thank you both for your replies and for your patience.

One more request – I want to confirm which iOS SDK you're using with Xcode. Would you mind sending me a screenshot from Apple Menu > About this Mac >System Report button > Software > Developer: 

![image](https://cloud.githubusercontent.com/assets/17483354/20148959/eb342e9c-a663-11e6-944e-e9cb724726be.png)

Just want to rule out some more basics. Thanks for bearing with me.

**Comment by mylaneza** [comment] 2016-11-09 18:13
2016-11-09 12:06 GMT-06:00 Stephen Cobbe <notifications@github.com>:

**Comment by holyman2k** [comment] 2016-11-10 02:52
<img width="261" alt="screen shot 2016-11-10 at 1 52 20 pm" src="https://cloud.githubusercontent.com/assets/729313/20162984/ef4bd310-a74c-11e6-985b-5e2e3a973271.png">

**Comment by scobbe** [comment] 2016-11-10 02:57
@holyman2k: Thanks for the reply.

Is there anyway that you might be compiling with an older iOS SDK? I'm not totally sure how that might happen, but maybe an older version of Xcode or something is getting in the way.

Last sanity check for you:

![image](https://cloud.githubusercontent.com/assets/17483354/20163055/4c017708-a6ae-11e6-978b-2f9db91c23a3.png)

I want to make sure that you're getting your frameworks (here, `Foundation.framework`) from an iOS SDK >= 8. What path is your `Foundation.framework` linking with?

Mine is: `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework`

Thanks for your patience!

**Comment by holyman2k** [comment] 2016-11-10 03:34
Hey Scobbe

Here is the screenshot, also also tried on a new project with no code just a single pod

![screen shot 2016-11-10 at 2 33 28 pm](https://cloud.githubusercontent.com/assets/729313/20163710/b0d993aa-a752-11e6-8cad-5c5146fcda54.png)

**Comment by scobbe** [comment] 2016-11-10 22:43
@holyman2k: Ok, thanks again. This is helpful. Would you mind attaching the full build logs of your project here? We should be able to get to the bottom of it with the logs. Thanks again for your patience.

**Comment by mylaneza** [comment] 2016-11-11 00:29
Do you mean this?

2016-11-10 16:43 GMT-06:00 Stephen Cobbe <notifications@github.com>:

**Comment by holyman2k** [comment] 2016-11-11 01:29
Scobbe, do you mean the build error log? Anyway, I've included both

![screen shot 2016-11-11 at 12 27 15 pm](https://cloud.githubusercontent.com/assets/729313/20201192/3a01a476-a80a-11e6-9142-f1e2c9e318a1.png)

[Build Writer_2016-11-11T11-21-29.docx](https://github.com/dropbox/dropbox-sdk-obj-c/files/584846/Build.Writer_2016-11-11T11-21-29.docx)

**Comment by scobbe** [comment] 2016-11-12 00:21
@holyman2k: Yes, perfect. Thanks for this. I suspect that your framework search path variable might be the source of the problem.

@mylaneza: It'd be great if you could reply via the website, rather than email. It looks like your images are not going through when you reply via email.

Would you both of you mind sending me the output of the following two commands:
- `xcode-select -p`
- `xcodebuild -project <MY_PROJECT>.xcodeproj -target "<MY_PROJECT_TARGET>" -showBuildSettings > build_settings.txt`

This should be my last request from you two. Thanks for your patience!

**Comment by scobbe** [comment] 2016-11-12 00:35
@mylaneza: Oh and if you send me your **full** build logs, that would be amazing.

Use the following **Save...** button:

![image](https://cloud.githubusercontent.com/assets/17483354/20234028/151c75de-a82b-11e6-8d5a-d0852ab2075d.png)

Thanks in advance!

**Comment by holyman2k** [comment] 2016-11-12 02:32
Scobbe, it's the Build Writer_2016-11-11T11-21-29.docx, I can't upload rtf, so i converted it to docx

**Comment by holyman2k** [comment] 2016-11-13 22:27
@scobbe: please see details below:

![screen shot 2016-11-14 at 9 25 27 am](https://cloud.githubusercontent.com/assets/729313/20249392/51a8f5b8-aa4c-11e6-8d3a-45a8a29a4a85.png)
[build.txt](https://github.com/dropbox/dropbox-sdk-obj-c/files/588127/build.txt)

**Comment by mylaneza** [comment] 2016-11-14 18:43
Here it is 


[Build_2016-11-14T12-39-44.txt](https://github.com/dropbox/dropbox-sdk-obj-c/files/590191/Build_2016-11-14T12-39-44.txt)

**Comment by scobbe** [comment] 2016-11-15 07:03
@holyman2k: Thanks again for your reply.

Looks like your `FRAMEWORK_SEARCH_PATHS` variable is somehow missing the path for where `ObjectiveDropboxOfficial.framework` is.

Try adding `"$PODS_CONFIGURATION_BUILD_DIR/ObjectiveDropboxOfficial"` to your **Framework Search Paths** under ** Your Project** > **Your Build Target** > **Build Settings** > **All**.

![image](https://cloud.githubusercontent.com/assets/17483354/20296230/76899eec-aabe-11e6-9e7c-28bc57e4707b.png)

Let me know if this solves your issue. Thanks for your patience!

**Comment by scobbe** [comment] 2016-11-15 07:03
@mylaneza: Would you mind sending me the output of the following two commands:
- `xcode-select -p`
- `xcodebuild -project <MY_PROJECT>.xcodeproj -target "<MY_PROJECT_TARGET>" -showBuildSettings > build_settings.txt`

Thanks!

**Comment by mylaneza** [comment] 2016-11-15 16:21
Here you go 
[xcodeselectoutput.txt](https://github.com/dropbox/dropbox-sdk-obj-c/files/592535/xcodeselectoutput.txt)
[build_settings.txt](https://github.com/dropbox/dropbox-sdk-obj-c/files/592536/build_settings.txt)

**Comment by scobbe** [comment] 2016-11-15 19:43
@holyman2k: You said that you've experienced this issue on a plain project as well when using CocoaPods? Could I ask one more favor of you – would you mind zipping the plain project with the Webkit issue on it and attach it here? I'm having a lot of trouble identifying what's the issue here...

Thank you!

**Comment by holyman2k** [comment] 2016-11-16 05:45
@scobbe here is the project
[TestDropbox.zip](https://github.com/dropbox/dropbox-sdk-obj-c/files/593833/TestDropbox.zip)

**Comment by mylaneza** [comment] 2016-11-16 20:04
@scobbe in case you did not see them

[xcodeselectoutput.txt](https://github.com/dropbox/dropbox-sdk-obj-c/files/595783/xcodeselectoutput.txt)
[build_settings.txt](https://github.com/dropbox/dropbox-sdk-obj-c/files/595784/build_settings.txt)

**Comment by eddie129** [comment] 2016-11-28 10:28
@scobbe I have same problem on my case-sensitive computer. After downloading source files and do some test, the problem can be fixed by updating 'Webkit' to 'WebKit' (upper case K)  in ObjectiveDropboxOfficial.podspec line 21&22. Cloud you verify it and update a new version? Thanks.

**Comment by scobbe** [comment] 2016-12-01 07:16
@holyman2k @mylaneza: Sorry this has dragged out for so long.

Looks like @eddie129 has come up with a fix – many thanks!

Would you all try pulling the (just-released) latest version of the SDK (2.0.0) and see if you still experience these issues? Thanks for your patience through all of this

**Comment by mylaneza** [comment] 2016-12-01 19:01
i am using cocoapods. Using Cocoapods the problem is still present. 

pod 'ObjectiveDropboxOfficial'

**Comment by scobbe** [comment] 2016-12-01 19:12
@mylaneza: Thanks for your reply.

Could you confirm that your error is `ld: framework not found WebKit` and NOT `ld: framework not found Webkit` (note the lower case 'k' in the second message)

**Comment by mylaneza** [comment] 2016-12-01 19:30
![screen shot 2016-12-01 at 1 29 37 pm](https://cloud.githubusercontent.com/assets/11892898/20809008/5189950c-b7ca-11e6-90e5-5880f95edffa.png)

**Comment by mylaneza** [comment] 2016-12-01 19:33
@scobbe Do you want me to add the dropbox api directly to my project instead of using cocoapods?

**Comment by scobbe** [comment] 2016-12-01 19:47
@mylaneza: Ok, fortunately it looks like you're still getting the old version of ObjectiveDropboxOfficial.

Would you please perform the following for me (in your project directory):

`rm -rf "${HOME}/Library/Caches/CocoaPods"`
`rm -rf Pods/`
`rm Podfile.lock`
`rm -rf <MY_PROJECT>.xcworkspace`

Then, with a correctly formatted Podfile in your .xcproject directory (see [here](https://github.com/dropbox/dropbox-sdk-obj-c#user-content-cocoapods)):

`pod install`

Then let me know if you still receive this error...

**Comment by scobbe** [comment] 2016-12-01 19:48
This should pull the latest version of ObjectiveDropboxOfficial (v2.0.1)

**Comment by mylaneza** [comment] 2016-12-01 20:22
@scobbe I followed your instructions. The same version 1.1.1. I am trying right now to use pod update.

**Comment by mylaneza** [comment] 2016-12-01 20:31
@scobbe pod update worked fine. Thank you very much.

**Comment by scobbe** [comment] 2016-12-01 21:12
@mylaneza: Amazing, great to hear. Sorry this was so painful! Let us know if anything else comes up.

@holyman2k: Let me know if you're still running into issues on your end.

**Comment by scobbe** [comment] 2016-12-01 22:22
and thanks again to @eddie129 for the great catch! This issue was really bugging me.

**Comment by scobbe** [comment] 2016-12-06 18:06
@holyman2k: Just want to check back in with you here and see if your problem is resolved with the latest version of the SDK?

**Closed** 2016-12-16 04:35 UTC
