### ISSUE TITLE
Is this official release?

### ISSUE THREAD

**Issue by amoshsueh** [dropbox/dropbox-sdk-obj-c#25] opened 2016-09-06 02:53 UTC
1. ObjectiveDropboxOfficial is not found in CocoaPod, only ObjectiveDropbox is available.
2. No DropboxSDKImports.h for import.
3. No DropboxClientsManager class or 'setupWithAppKey' api.

I can't use this SDK, please help!

**Comment by scobbe** [comment] 2016-09-06 06:22
Hi @amoshsueh, sorry about the trouble you're experiencing. Please try re-running the CocoaPods command. The production release of the SDK was not on the CocoaPods server a few hours ago. Please try again now and let me know if the problem is solved.

**Comment by xaphod** [comment] 2016-09-07 03:28
@scobbe  It is not working for me either: when I use the master cocoapods repo, I can get the ObjectiveDropboxOfficial pod, but it only contains a LICENSE and README.md. 
Please check the podspec you pushed to the cocoapods master repo, probably it has a wrong version number, or, you've tagged something wrong

**Comment by scobbe** [comment] 2016-09-07 05:11
@xaphod: Things for the ping. Yup, you're right, issue with the version number. Should be fixed now.

**Comment by amoshsueh** [comment] 2016-09-07 12:12
@scobbe The problem is solved, thanks.

**Closed** 2016-09-07 12:12 UTC
