### ISSUE TITLE
v1_retired errors

### ISSUE THREAD

**Issue by guidedways** [dropbox/dropbox-sdk-obj-c#173] opened 2017-10-01 15:36 UTC
Hi

Many of our users are being annoyed by a v1_retired error even though they are not using v1 APIs (they've got our latest app which does not use v1 at all). It does 'migrate' a v1 token if there's one but it does not sync using v1 APIs.

We've asked them to unlink and relink and they're frustrated as much as we are. Please help.

**Comment by greg-db** [comment] 2017-10-02 01:22
Thanks for the report! This SDK only calls API v2 endpoints, so that would be unexpected.

Can you share the code that reproduces the issue, and any output errors you get?

Also, are you sure they're definitely on the latest version of your app(s)? It sounds like they just may be on older versions, which would be using older (v1) SDKs.

**Comment by guidedways** [comment] 2017-10-02 01:23
I've asked some of them for their logs but they say they're most certainly on the latest version. Some of them are reporting Dropbox 400 errors and some are reporting v1_retired, while some other are reporting v1_something errors. It's all over the place, given the number of people syncing with dropbox. Yet I'm unable to reproduce this on my own devices.

**Comment by greg-db** [comment] 2017-10-02 01:27
Ok, thanks for the information. In that case, since you can't reproduce this, I'll close this and follow up with you privately after checking our logs.

**Closed by greg-db** 2017-10-02 01:27 UTC
