### ISSUE TITLE
Dropbox added from pod but download image function not working

### ISSUE THREAD

**Issue by puneettest** [dropbox/dropbox-sdk-obj-c#161] opened 2017-06-19 12:55 UTC
I have attached dropbox in my project from pod and all things working fine but when try to download the image its returning nil.  So please let me know how i can resolve this problem.

```
- (void)downloadImage:(NSString *)imagePath fileName:(NSString*)fileName {
    NSLog(@"puneet path %@  file name %@",imagePath,fileName);
    DBUserClient *client = [DBClientsManager authorizedClient];
    [[client.filesRoutes downloadData:imagePath]
     setResponseBlock:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, DBRequestError *error, NSData *fileData) {
     
}

```
in this method filedata is nil so image is not downloading. So please let me know how i can resolve this.

Thanks

**Comment by scobbe** [comment] 2017-06-19 17:20
@puneettest: Thanks for reaching out. Usually if the result is `nil`, then there is some error. Can you print out `routeError` and `error` in your response block, and share those values here?

**Comment by puneettest** [comment] 2017-06-20 06:18
Hello Scobbe
When  downloadImage function call then its not returning any error both  error and routeError is nil. also result is contain the metadata of the image but filedata is nil. 

result contain this:
Printing description of result:
{
    "client_modified" = "2015-09-14T13:37:05Z";
    "content_hash" = 96cd5fddeb194c4b704b1ebceaaea73f1008c8e016308e1518dbb54f4316c19d;
    id = "id:KFg21KDAOqAAAAAAAAAD2A";
    "media_info" =     {
        ".tag" = metadata;
        metadata =         {
            ".tag" = photo;
            dimensions =             {
                height = 1758;
                width = 750;
            };
            "time_taken" = "2015-09-14T15:44:48Z";
        };
    };
    name = "07_b.jpg";
    "path_display" = "/Appartment/App Design/07_b.jpg";
    "path_lower" = "/appartment/app design/07_b.jpg";
    rev = 50a341a3a90;
    "server_modified" = "2015-09-14T13:37:05Z";
    size = 251931;
}


Also path and file name 
 path   /appartment/app design/07_b.jpg    
 file name     07_b.jpg

so please check and let me know your view.

Thanks

**Comment by scobbe** [comment] 2017-06-20 06:46
Ok, thanks for the detailed information. We'll investigate further. And you're able to reproduce this on multiple different .jpg files?

**Comment by puneettest** [comment] 2017-06-20 06:50
Yes this error comes on multiple different  .jpg , .png files .

**Comment by greg-db** [comment] 2017-06-20 23:30
Thanks @puneettest . I tried reproducing this using your code though, and I don't get a `nil` `fileData` as you described.

To help us investigate further, can you share:
- the version of Xcode you're using.
- the version of iOS you're using.
- the version of the API v2 Objective-C SDK you're using.
- the rest of the code you're using to call and check this. (Your shared code doesn't include any of your code inside the response block.)

Thanks in advance!

**Comment by puneettest** [comment] 2017-06-21 07:08
Xcode version is 8.2.
iOS versio - 10.2
Objective-C SDK version - 3.0.15

The following code goes inside the block:-
if (result) {        
     NSString* path = [self photoPath:fileName];
     [fileData writeToFile:path atomically:YES];
         
     imgLocation.image=[UIImage imageWithContentsOfFile:path];        
     finalImageData = UIImageJPEGRepresentation([UIImage imageWithContentsOfFile:path], 0.0);    
     [self.navigationController pushViewController:edit animated:YES];
}

and the method photoPath is:-
- (NSString*)photoPath:(NSString *)strFileName {
    NSLog(@"%@",[NSTemporaryDirectory() stringByAppendingPathComponent:strFileName]);
    return [NSTemporaryDirectory() stringByAppendingPathComponent:strFileName];
}

i'm attaching a screenshot that shows fileData being nil.
![screen shot 2017-06-21 at 12 32 44 pm](https://user-images.githubusercontent.com/29457749/27371442-72593730-567e-11e7-872d-ee4e155d3ef5.png)

Thanks!

**Comment by scobbe** [comment] 2017-06-21 17:29
Thanks! We're looking into this now. In the meantime, please update from 3.0.15 to the latest version of the SDK, and let us know if the problem persists. Thanks!

**Comment by greg-db** [comment] 2017-06-21 18:33
Thanks for the information @puneettest . I can reproduce this in v3.0.15, and not 3.1.2, so it looks like it was already fixed, so please update your SDK. I'll close this accordingly.

**Closed by greg-db** 2017-06-21 18:33 UTC
